"""Structure of the teaching volume: every skill, explained."""

BOOK = {
    "title": "The AI/ML Engineering Handbook",
    "subtitle": "Every skill on the map, taught from first principles",
    "cover_title": ["The AI/ML", "Engineering", "Handbook"],
    "cover_sub": ["Every skill an AI/ML engineer needs,",
                  "explained properly — from Python packaging",
                  "to speculative decoding."],
    "kicker": "THE COMPLETE TEACHING VOLUME",
    "author": "Volume III · with Data Structures & Algorithms and The Skill Map",
    "edition": "First edition · 2026",
    "tagline": ("The Skill Map says what to learn. This book teaches it. Every "
                "competency is built from the ground up: the idea, why it "
                "works, the code, the failure modes, and the exercises that "
                "turn reading into ability."),
    "frontmatter": ["fm-how-to-learn.md"],
}

PARTS = [
    {"n": 1, "roman": "I", "title": ["The Engineering", "Foundation"],
     "blurb": ["Before any model: the craft of writing software that other",
               "people — and your future self — can run, trust and change.",
               "This is the layer that separates an engineer from a",
               "notebook author, and the one most often skipped."],
     "chapters": ["01-modern-python.md", "02-types-and-contracts.md",
                  "03-testing-ml-code.md", "04-environments.md",
                  "05-git-as-a-tool.md", "06-containers.md"]},

    {"n": 2, "roman": "II", "title": ["The Mathematics", "You Actually Use"],
     "blurb": ["Not a mathematics course: the specific results you reach for",
               "weekly, derived far enough that you can debug with them.",
               "Every idea is introduced through a thing it explains about",
               "a model you have already run."],
     "chapters": ["07-linear-algebra.md", "08-calculus-backprop.md",
                  "09-probability.md", "10-statistics.md",
                  "11-optimisation.md"]},

    {"n": 3, "roman": "III", "title": ["Data"],
     "blurb": ["Where most of the hours go, most of the value is created,",
               "and almost all irreproducible results come from. Query",
               "engines, dataframes at scale, pipelines that do not lie,",
               "and the curation of a training corpus."],
     "chapters": ["12-sql-and-engines.md", "13-dataframes-at-scale.md",
                  "14-pipelines.md", "15-features-and-skew.md",
                  "16-curating-a-corpus.md"]},

    {"n": 4, "roman": "IV", "title": ["Classical", "Machine Learning"],
     "blurb": ["Still most of the ML running in production, and the source",
               "of every idea that later gets reinvented with a new name.",
               "Generalisation, linear models, gradient boosting,",
               "calibration, and explaining a decision."],
     "chapters": ["17-the-learning-problem.md", "18-linear-models.md",
                  "19-trees-and-boosting.md", "20-calibration.md",
                  "21-explaining-models.md"]},

    {"n": 5, "roman": "V", "title": ["Deep Learning"],
     "blurb": ["From the tensor to a transformer you have written yourself,",
               "then the training loop, the modern component library, the",
               "debugging playbook, and what changes when one GPU is no",
               "longer enough."],
     "chapters": ["22-tensors-and-autograd.md", "23-the-training-loop.md",
                  "24-architectures.md", "25-the-transformer.md",
                  "26-modern-components.md", "27-debugging-training.md",
                  "28-training-at-scale.md"]},

    {"n": 6, "roman": "VI", "title": ["Foundation Models"],
     "blurb": ["What is actually happening inside a model you call over an",
               "API, what each call costs and why, and the four ways to",
               "make one do your task: prompting, structure, retrieval",
               "and training."],
     "chapters": ["29-tokenisation-and-context.md", "30-the-forward-pass.md",
                  "31-prompting-as-engineering.md", "32-structure-and-tools.md",
                  "33-retrieval.md", "34-building-rag.md",
                  "35-supervised-finetuning.md", "36-preference-optimisation.md"]},

    {"n": 7, "roman": "VII", "title": ["Making It Real"],
     "blurb": ["The half of the job that decides whether any of the above",
               "was worth doing: measuring honestly, running agents that",
               "do not wander, serving cheaply, deploying safely, and",
               "knowing where the time actually goes."],
     "chapters": ["37-evaluation.md", "38-statistics-of-evaluation.md",
                  "39-agents.md", "40-inference.md",
                  "41-compression.md", "42-serving-and-mlops.md",
                  "43-hardware.md"]},

    {"n": 8, "roman": "VIII", "title": ["Judgement"],
     "blurb": ["The skills with no library: securing a system against its",
               "own inputs, working inside the regulatory surface,",
               "explaining yourself to people who will not read the code,",
               "and recognising when the answer is not to build this."],
     "chapters": ["44-security.md", "45-privacy-and-compliance.md",
                  "46-communication.md", "47-when-not-to.md"]},
]
